apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30700
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-cluster-service
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    app: webapp